server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    export:
      prometheus:
        enabled: true
grpc:
  server:
    port: ${GRPC_SERVER_PORT:8090}
spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

application:
  landscape:
    url: ${LANDSCAPE_URL}
