server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    export:
      prometheus:
        enabled: true
grpc:
  client:
    rancherService:
      address: ${RANCHER_GRPC_SERVER_ADDRESS:localhost:8090}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    handymanService:
      address: ${HANDYMAN_GRPC-SERVER_ADDRESS:localhost:8091}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml