server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    export:
      prometheus:
        enabled: true
grpc:
  client:
    rancherService:
      address: 'static://127.0.0.1:8090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    handymanService:
      address: 'static://127.0.0.1:8091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext